#DENTRO DE ESTE ARCHIVO VA COSAS GENERALES, LOS DRIVERS LOS MODELOS LA DIRECCION COMO TAL
#NADA ESPECIFICO DE CONFIGURACION DE DESARROLLO COMO CONFIGURACION
# DE QUE BASE DE DATOS INICIAR O QUE LOG SDESEAMOS VERIFICAR

spring.profiles.active=prod
spring.application.name=platzi-play
server.servlet.context-path=/platzi-play/api

#postgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
#langchai4js
#este es el modelo que vamos a utilizar
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
