server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d9gksdjbc2fs738opitg-a/platzi_play_db_cewg

spring.datasource.username=angel
spring.datasource.password=HJmm6pkepRReGeQCGuzVNsv2DIWgF7fV

spring.jpa.hibernate.ddl-auto=update

langchain4j.open-ai.chat-model.api-key=demo
