
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/platzi_play_db
spring.datasource.username=angel
spring.datasource.password=angel.platzi

#crear tabla si no existe
spring.jpa.hibernate.ddl-auto=update
#muestre en consola lo que esta haciendo
spring.jpa.show-sql=true
#muestre en consola lo que esta haciendo y se entienda en sql
spring.jpa.properties.hibernate.format_sql=true

#siempre inicializa los datos, en caso de que el sql tenga  ON CONFLICT (titulo) DO NOTHING; no registrara ese dato si ya esta en la base
#Propiedad para inicializar datos al arrancar de data.sql
spring.sql.init.mode=always

#langchai4js
#este sirve para saber que api key vamos a usar
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG

